---
title: "Assignment 3 - Task 4"
author: "Jessica West"
date: "10/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(tidyverse)
library(janitor)
library(here)
library(lubridate)
library(plotly)
library(kableExtra)
```

```{r}
urchins_kelp <- read_csv(here("data", "urchins.csv"))
clean_urchins_kelp <- clean_names(urchins_kelp)
```

```{r}
urchins_kelp__napl_2010 <- clean_urchins_kelp %>% 
    mutate(date_new = mdy(date)) %>% 
  mutate(year_new = year(date_new)) %>%
  filter(common_name == "Purple Urchin", 
         site == "NAPL", 
         year_new == "2010", 
         treatment == "CONTROL" | treatment == "ANNUAL") %>% 
  group_by(treatment)

ggplot(data = urchins_kelp__napl_2010, aes(x = size)) + 
  geom_histogram(fill="blue", color = "black", bins = 10) +
     facet_wrap(~ treatment) +
  theme_classic()

ggplot(data = urchins_kelp__napl_2010, aes(sample = size)) +
  geom_qq() +
  facet_wrap(~ treatment) +
  theme_classic()
```

The above figures show differences between purple urchin size as a result of annual and control kelp treatment. Both the annual and control treatments appear to be not-quite evenly distributed for purple urchin populations with relatively larger/wider standard deviations (~99%).

```{r}
urchin_kelp_stats <- urchins_kelp__napl_2010 %>% 
  group_by(treatment) %>% 
  summarize(mean = mean(size),
            median = median(size),
            sd = sd(size),
            sample_size = n())

urchin_kelp_stats %>% 
  kable(caption = "Size Comparison of Purple Urchins in Naples Reef (2010)", 
      col.names = c("Treatment", "Mean (cm)", "Median (cm)", "Standard Deviation (cm)", "Sample Size")) %>%  
  kable_styling(full_width = FALSE)
```
